[supervisord]
nodaemon=true

[program:mongodb]
command=/usr/bin/mongod --dbpath=/data/db --bind_ip_all
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:website]
command=npm run dev
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr